// Icons
import {
  FaInstagram,
  FaFacebook,
  FaTwitter,
  FaLinkedinIn,
  FaYoutube,
  FaTiktok,
} from "react-icons/fa";

// SosialLinks
export const contentSocialLinks = [
  {
    id: 1,
    label: "Instagram",
    icon: FaInstagram,
    url: "/",
  },
  {
    id: 2,
    label: "Facebook",
    icon: FaFacebook,
    url: "/",
  },
  {
    id: 3,
    label: "Twitter",
    icon: FaTwitter,
    url: "/",
  },
  {
    id: 4,
    label: "LinkedIn",
    icon: FaLinkedinIn,
    url: "/",
  },
  {
    id: 5,
    label: "YouTube",
    icon: FaYoutube,
    url: "/",
  },
  {
    id: 6,
    label: "TikTok",
    icon: FaTiktok,
    url: "/",
  },
];

// Navbar Menu
export const MainNav = [
  {
    id: 1,
    label: "Beranda",
    media: null,
    icon: null,
    url: "/",
    subLinks: null,
  },
  {
    id: 2,
    label: "Produk & Layanan",
    media: null,
    icon: null,
    url: "/",
    subLinks: [
      {
        id: 1,
        label: "Dana Tunai",
        media: "dana-tunai.svg",
        icon: null,
        url: "/",
        subLinks: [
          {
            id: 1,
            label: "Pinjam Online",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 2,
            label: "GoPay",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 3,
            label: "OVO",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 4,
            label: "LinkAja",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 5,
            label: "ShopeePay",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 6,
            label: "DANA",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
        ],
      },
      {
        id: 2,
        label: "Paylater",
        media: "paylater.svg",
        icon: null,
        url: "/",
        subLinks: [
          {
            id: 1,
            label: "Tokopedia",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 2,
            label: "Bukalapak",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 3,
            label: "Shopee",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 4,
            label: "Lazada",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 5,
            label: "BliBli",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 6,
            label: "Tiket Kereta",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
        ],
      },
      {
        id: 3,
        label: "Tagihan Online",
        media: "tagihan-online.svg",
        icon: null,
        url: "/",
        subLinks: [
          {
            id: 1,
            label: "Listrik",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 2,
            label: "Pulsa & Data",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 3,
            label: "Pascabayar",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 4,
            label: "BPJS",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 5,
            label: "PDAM",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
          {
            id: 6,
            label: "Pendidikan",
            media: null,
            icon: null,
            url: "/",
            subLinks: null,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    label: "Tentang Kami",
    media: null,
    icon: null,
    url: "/",
    subLinks: null,
  },
  {
    id: 4,
    label: "Berita & Tips",
    media: null,
    icon: null,
    url: "/",
    subLinks: null,
  },
  {
    id: 5,
    label: "Promo",
    media: null,
    icon: null,
    url: "/",
    subLinks: null,
  },
  {
    id: 6,
    label: "Bantuan",
    media: null,
    icon: null,
    url: "/",
    subLinks: null,
  },
  {
    id: 6,
    label: "Karir",
    media: null,
    icon: null,
    url: "/",
    subLinks: null,
  },
];

export const footerMenu = [
  {
    id: 1,
    title: "JULO Kredit Digital",
    links: [
      {
        id: 1,
        label: "Tentang Kami",
        accent: "",
        url: "/",
      },
      {
        id: 2,
        label: "Berita & Tips",
        accent: "",
        url: "/",
      },
      {
        id: 3,
        label: "Bantuan",
        accent: "",
        url: "/",
      },
      {
        id: 4,
        label: "Promo",
        accent: "",
        url: "/",
      },
      {
        id: 5,
        label: "Karir",
        accent: "We Are Hiring!",
        url: "/",
      },
    ],
  },
  {
    id: 2,
    title: "Produk & Layanan",
    links: [
      {
        id: 1,
        label: "Dana Tunai",
        accent: "",
        url: "/",
      },
      {
        id: 2,
        label: "Paylater",
        accent: "",
        url: "/",
      },
      {
        id: 3,
        label: "Tagihan Online",
        accent: "",
        url: "/",
      },
    ],
  },
  {
    id: 3,
    title: "Lainnya",
    links: [
      {
        id: 1,
        label: "Syarat & Ketentuan",
        accent: "",
        url: "/",
      },
      {
        id: 2,
        label: "Kebijakan Privasi",
        accent: "",
        url: "/",
      },
      {
        id: 3,
        label: "Laporan Penipuan",
        accent: "",
        url: "/",
      },
      {
        id: 4,
        label: "Cara Membayar",
        accent: "",
        url: "/",
      },
    ],
  },
];
