import "./globals.css";
import type { Metadata } from "next";
import { Montserrat as FontDisplay, Hind as FontBody } from "next/font/google";

import { cn } from "@/lib/utils";

const fontDisplay = FontDisplay({
  subsets: ["latin"],
  variable: "--font-display",
});

const fontBody = FontBody({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen font-body antialiased",
          fontDisplay.variable,
          fontBody.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
